spring:
  profiles:
    group:
      default: test
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.springframework.data.mongodb.repository.query: debug