spring:
  profiles:
    group:
      default: LOGGING_CONSOLE
  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    import: optional:classpath:security.yml
  application:
    name: api
  data:
    mongodb:
      auto-index-creation: true
      database: daymotion
  r2dbc:
    url: r2dbc:mysql://4sitive.mysql.database.azure.com:3306/daymotion?sslMode=disabled&connectTimeout=PT2S&tcpKeepAlive=true&tcpNoDelay=true&serverZoneId=Asia/Seoul&characterEncoding=utf8
    username: db_admin
    pool:
      initial-size: 1
      max-size: 1
      max-create-connection-time: PT2S
      max-acquire-time: PT2S
      max-idle-time: PT180S
      validation-query: SELECT 1
      validation-depth: REMOTE
  mongodb:
    embedded:
      version: 4.0.12
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
logging:
  level:
    SQL: trace
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
    org.springframework.data.mongodb.repository.query: debug
server:
  forward-headers-strategy: framework
  port: 8080
management:
  server:
    port: 8081